// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llssfiurupclhpiaozug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsc3NmaXVydXBjbGhwaWFvenVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTQwNDUsImV4cCI6MjA1NDc5MDA0NX0.FHHyZskc0QUGVxgJU-duEtIJiUgwQQjFq9F83xJ4Rtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);